---

- name: Install dnsmasq
  package: name=dnsmasq state=present

- name: Copy dnsmasq config
  template: src=etc/{{ item }}.j2 dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - dnsmasq.conf
    - hosts.dnsmasq
  register: dnsmasq_register_config

- name: Restart dnsmasq
  service: name=dnsmasq state=restarted
  when: dnsmasq_register_config.changed
